---
- name: Download Grafana .deb package
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_9.5.1_amd64.deb"
    dest: "/tmp/grafana_9.5.1_amd64.deb"
    mode: '0644'

- name: Install Grafana .deb package
  apt:
    deb: "/tmp/grafana_9.5.1_amd64.deb"

- name: Ensure Grafana is started and enabled
  systemd:
    name: grafana-server
    enabled: yes
    state: started

