FROM python:3.10-alpine

RUN apk update && apk upgrade && apk add --no-cache bash

WORKDIR /home/test

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD [ "python","app.py" ]